storage:
  # EBEANS - Ebeans storage (will go to SqlLite or MySQL, as defined
  #     by bukkit.yml)
  # YAML - YAML storage in your plugins/HomeSpawnPlus directory.
  #     Will store one file per data type (home, spawn, etc).
  # YAML_SINGLE_FILE - YAML storage in your plugins/HomeSpawnPlus
  #     directory. Stores all data in single "data.yml" file.
  # PERSISTANCE_REIMPLEMENTED_EBEANS - use persitance reimplemented
  #     ebeans implementation. Exactly like EBEANS above except with
  #     a few extra benefits. http://goo.gl/rtdDH  To live-reload
  #     with this, due to a Bukkit limitation, you must edit
  #     plugin.yml and set 'database: false'
  #
  # This is one option that cannot be reloaded live with "/hsp rc",
  # you must restart Bukkit if you change this option.
  type: EBEANS
