documentation: 'http://dev.bukkit.org/server-mods/homespawnplus/pages/config-params'

# If you're having problems with other plugins that have registered commands
# that you want to use with HSP (for example, CommandBook has /home, /spawn
# and loads first alphabetically), you can uncomment the below lines and
# HSP will then take over those commands for it's own use when it loads.
#usurpCommands:
#  - home
#  - sethome
#  - spawn
#  - setspawn

core:
  # 0 - Ebeans storage (will go to SqlLite or MySQL, as defined
  #     by bukkit.yml)
  # 1 - Cached Ebeans - same as #0, but with in-memory caching
  #     for performance
  # Don't use Cached for now, might be buggy and eBeans has built-in
  # caching so it should be just as fast unless you have 10's of
  # thousands of entries
  storage: 0

  # this is ONLY used when a Permissions-compatible plugin isn't found.
  # In that case, any permissions listed here are given to everyone by
  # default (ops always have full permissions)
  defaultPermissions:
    - hsp.command.home.use 
    - hsp.command.sethome.use 

  homeMode: SINGLE_MULTIWORLD

  # set to true to enable players setting their homes by clicking beds.
  # they must also have the 'hsp.home.bedsethome' permission.
  bedsethome: true
  # if this is true and bedsethome is true, sleeping in a bed will
  # change the player "default" home. If you want players to be
  # able to sleep in a bed to set their "bed" home but not have it
  # change their "default" home when they do so, set this to false.
  bedSetsDefault: true
 
  # The default world.  This world is used anywhere you see "global
  # spawn" referenced below and also in the event all else fails (no
  # home set, no spawn set in current world, etc), a player will be
  # sent to the spawn in whatever world you define here.
  defaultWorld: world

  # set to true if you want plugin to change the spawn of the actual map
  # (ie. even if you turn this plugin off later, whatever default spawn
  # you set in various worlds will stay)
  override_world: true

  # if recordLastLogout is true, the plugin will record the precise
  # location the player logged out at and respawn them there, instead
  # of just letting Bukkit do it. This is an attempt to work around a
  # bug where people logout close to a wall and Bukkit tries to respawn
  # them in the wall
  recordLastLogout: false

  # set to true to enable group spawn functionality.  When set, you can
  # use the /setgroupspawn [group] command to set spawns for specific
  # groups.  Maybe useful for RPG classes, PvP factions, whatever.
  groupSpawnEnabled: false

  # set to true to have a bit more verbose logging in your server.log
  # about what HomeSpawnPlus is doing
  verboseLogging: false
  verboseStrategyLogging: false

# The events below allow use of the strategies described here. Web
# doc reference:
# http://dev.bukkit.org/server-mods/homespawnplus/pages/strategy-doc/
#
events:
  # strategies to use when player is joining the game
  onJoin:
    - spawnNewPlayer
    - default
 
  # strategies to use when player is respawning after a death
  onDeath:
    - homeMultiWorld
    - spawnLocalWorld

  # strategies to use when player types "/spawn"
  onSpawnCommand:
    - spawnLocalWorld
    - spawnDefaultWorld

  # strategies to use when player types "/groupspawn"
  onGroupSpawnCommand:
    - spawnGroup

  # CURRENTLY NOT USED, to be added in future version
  onHomeCommand:
    - homeMultiWorld

# you can globally enable/disable individual commands here.
# permissions for each command are: hsp.command.<commandName>.use
# for example to let players use "/home", you would give them:
# 
#   hsp.command.home.use
#
disabledCommands:
  home: false
  sethome: false
  spawn: false
  setspawn: false
  groupspawn: false
  setgroupspawn: false

# cooldowns for various commands can be defined here (these are used if
# no group-specific cooldown permissions are found)
#
# Cooldown exemption permissions are:
#   hsp.command.CooldownExempt.<commandName>   - can use * to be exempt
#     from all cooldowns
#   
cooldown:
  home: 60
  spawn: 60
  groupspawn: 0

warmup:
  # globally enable or disable warmups. The other options have no effect
  # if this is not true. This flag exists as a performance enhancement
  # for those not wishing to use warmups, none of the extra event types
  # will be hooked at all. (This plugin is extremely efficient about
  # how it hooks & handles these events, but for those not using warmups
  # at all, no point in having even the small overhead associated with
  # processing these events)
  enabled: false
 
  # set to true if movement should cancel a warmup
  onMoveCancel: false

  # set to true if receiving damage should cancel a warmup
  onDamageCancel: false

  # individual command warmup timers
  home: 5
  spawn: 5

# If you have Vault installed, HSP can use that to charge prices for commands
# using whatever economy plugin you happen to have installed. Costs will not
# work if you do not have Vault installed.
#
# http://dev.bukkit.org/server-mods/vault/
cost:
  # if verbose is true, the player will get a message stating that their account
  # has been charged whenever they use a command with a cost.
  verbose: true
  home: 0
  sethome: 0
  spawn: 0
  groupspawn: 0
