name: HomeSpawnPlus
main: org.morganm.homespawnplus.HomeSpawnPlus
version: 0.9.1
author: morganm
database: true
softdepend: [Vault, WorldGuard]
commands:
  setspawn:
    description: Sets the spawn for this world
    usage: /<command>
  setdefaultspawn:
    description: Sets the default spawn to a named spawn
    usage: "/<command> [spawnname]"
  spawn:
    description: Respawns you at the world spawn
    usage: /<command>
  globalspawn:
    description: Respawns you at the global spawn (default world)
    usage: /<command>
  setgroupspawn:
    description: Sets the group spawn
    usage: |
        Incorrect usage of command /<command>. Examples:
           /<command> Admins - sets the group spawn for the 'Admins' group
  setfirstspawn:
    description: Sets the newPlayer spawn
    usage: /<command>
  groupspawn:
    description: Returns you to the group spawn
    usage: |
           Incorrect usage of command /<command>. Examples:
           /<command> - respawns you at your primary group spawn
           /<command> Admins - respawns you at the 'Admins' group spawn
  sethome:
    description: Sets your home
    usage: |
        Incorrect usage of command /<command>. Examples:
           /<command> - sets your home to your current location
           /<command> Bob - sets Bob's home to your current location            
  home:
    description: Respawns you at your home
    usage: /<command>
  hspconvert:
    description: Load and convert data from another data store
    usage: /<command>
  hsp:
    description: Load and convert data from another data store
    usage: /<command> [reloadconfig|reloaddata]
permissions:
    hsp.*:
        description: Gives access to all HomeSpawnPlus permissions
        children:
            hsp.home.bedsethome: true
            hsp.command.home.use: true
            hsp.command.home.others: true
            hsp.command.sethome.use: true
            hsp.command.sethome.others: true
            hsp.command.spawn.use: true
            hsp.command.setspawn.use: true
            hsp.command.setgroupspawn.use: true
            hsp.command.groupspawn.use: true
            hsp.command.CooldownExempt.home: true
            hsp.command.CooldownExempt.spawn: true
            hsp.command.CooldownExempt.groupspawn: true
            hsp.command.WarmupExempt.home: true
            hsp.command.WarmupExempt.spawn: true
            hsp.command.WarmupExempt.groupspawn: true
            hsp.command.CostExempt.groupspawn: true
            hsp.command.CostExempt.spawn: true
            hsp.command.CostExempt.home: true
            hsp.command.CostExempt.sethome: true
            hsp.command.setfirstspawn.use: true
    hsp.home.bedsethome:
        description: Allows a user to set home by right-clicking a bed
        default: true
    hsp.command.*:
        description: Gives access to all HomeSpawnPlus commands
        children:
            hsp.command.home.use: true
            hsp.command.home.others: true
            hsp.command.sethome.use: true
            hsp.command.sethome.others: true
            hsp.command.spawn.use: true
            hsp.command.setspawn.use: true
            hsp.command.setgroupspawn.use: true
            hsp.command.groupspawn.use: true
    hsp.command.home.use:
        description: Allows use of the /home command
        default: op
    hsp.command.home.others:
        description: Allows use of the /home command to teleport to other homes
        default: op
    hsp.command.sethome.use:
        description: Allows use of the /sethome command
        default: op
    hsp.command.sethome.others:
        description: Allows use of the /sethome command to set others homes
        default: op
    hsp.command.spawn.use:
        description: Allows use of the /spawn command
        default: op
    hsp.command.setspawn.use:
        description: Allows use of the /setspawn command
        default: op
    hsp.command.setfirstspawn.use:
        description: Allows use of the /setfirstspawn command
        default: op
    hsp.command.setgroupspawn.use:
        description: Allows use of the /setgroupspawn command
        default: op
    hsp.command.groupspawn.use:
        description: Allows use of the /groupspawn command
        default: op
    hsp.command.CooldownExempt.*:
        description: Exempt from all cooldowns
        children:
          hsp.command.CooldownExempt.home: true
          hsp.command.CooldownExempt.spawn: true
          hsp.command.CooldownExempt.groupspawn: true
    hsp.command.CooldownExempt.home:
        description: Exempt from /home cooldown
        default: op
    hsp.command.CooldownExempt.spawn:
        description: Exempt from /spawn cooldown
        default: op
    hsp.command.CooldownExempt.groupspawn:
        description: Exempt from /groupspawn cooldown
        default: op
    hsp.command.WarmupExempt.*:
        description: Exempt from all warmups
        children:
          hsp.command.WarmupExempt.home: true
          hsp.command.WarmupExempt.spawn: true
          hsp.command.WarmupExempt.groupspawn: true
    hsp.command.WarmupExempt.home:
        description: Exempt from /home warmup
        default: op
    hsp.command.WarmupExempt.spawn:
        description: Exempt from /spawn warmup
        default: op
    hsp.command.WarmupExempt.groupspawn:
        description: Exempt from /groupspawn warmup
        default: op
    hsp.command.CostExempt.*:
        description: Exempt from all costs
        children:
          hsp.command.CostExempt.home: true
          hsp.command.CostExempt.sethome: true
          hsp.command.CostExempt.spawn: true
          hsp.command.CostExempt.groupspawn: true
    hsp.command.CostExempt.home:
        description: Exempt from /home costs
        default: op
    hsp.command.CostExempt.sethome:
        description: Exempt from /sethome costs
        default: op
    hsp.command.CostExempt.spawn:
        description: Exempt from /spawn costs
        default: op
    hsp.command.CostExempt.groupspawn:
        description: Exempt from /groupspawn costs
        default: op
