name: HomeSpawnPlus
main: org.morganm.homespawnplus.HomeSpawnPlus
version: 0.7
author: morganm
database: true
commands:
  setspawn:
    description: Sets the spawn for this world
    usage: /<command>
  spawn:
    description: Respawns you at the world spawn
    usage: /<command>
  globalspawn:
    description: Respawns you at the global spawn (default world)
    usage: /<command>
  setgroupspawn:
    description: Sets the group spawn
    usage: |
        Incorrect usage of command /<command>. Examples:
           /<command> Admins - sets the group spawn for the 'Admins' group
  groupspawn:
    description: Returns you to the group spawn
    usage: |
           Incorrect usage of command /<command>. Examples:
           /<command> - respawns you at your primary group spawn
           /<command> Admins - respawns you at the 'Admins' group spawn
  sethome:
    description: Sets your home
    usage: |
        Incorrect usage of command /<command>. Examples:
           /<command> - sets your home to your current location
           /<command> Bob - sets Bob's home to your current location            
  home:
    description: Respawns you at your home
    usage: /<command>
  hspconvert:
    description: Load and convert data from another data store
    usage: /<command>
  hsp:
    description: Load and convert data from another data store
    usage: /<command> [reloadconfig|reloaddata]
